substitutions:
  name: <<your device name>>
  friendly_name: <<your device name>>
  ota_password: <<your device name>>
  key_encryption: <<your device name>>
  i2s_lrclk_ws: GPIO18
  i2s_bclk_sck: GPIO17
  mic: GPIO4
  spk: GPIO5
  ledpin: GPIO9
  numleds: "4"
  vol_up: GPIO21
  vol_down: GPIO47
  fallback_psw: "fallback_password"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: -100
    then:
      - script.execute:
          id: play_sound
          priority: true
          sound_file: !lambda return id(boot);
      - light.turn_on:
          id: status_led
          red: 0%
          green: 0%
          blue: 90%
          brightness: 80%
          effect: Scan
      - wait_until: api.connected
      - delay: 1s
      - voice_assistant.start_continuous:
      - light.turn_off: status_led

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended

psram:
  mode: octal
  speed: 80MHz

logger:

api:
  encryption:
    key: ${key_encryption}

ota:
  - platform: esphome
    password: ${ota_password}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name}-ap"
    password: "${fallback_psw}"


i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: ${i2s_lrclk_ws}
    i2s_bclk_pin: ${i2s_bclk_sck}

microphone:
  - platform: i2s_audio
    id: mic
    adc_type: external
    i2s_din_pin: ${mic}
    channel: left
    pdm: false
    i2s_audio_id: i2s_in
    bits_per_sample: 32bit

speaker:
  - platform: i2s_audio
    id: speakerid
    i2s_audio_id: i2s_in
    i2s_dout_pin: ${spk}
    dac_type: external
    channel: left
    bits_per_sample: 16bit
    buffer_duration: 80ms

media_player:
  - platform: speaker
    name: "Media player"
    id: media_playerid
    announcement_pipeline:
      speaker: speakerid
      format: WAV
    codec_support_enabled: false
    buffer_size: 6000
    volume_min: 0.5
    volume_increment: 0.25
    on_volume:
      then:
        - light.turn_on:
            id: status_led
            effect: "Volume Level Display"
        - delay: 1s
        - light.turn_off:
            id: status_led    
    files:
      - id: mute_switch_on_sound
        file: https://github.com/WarLion/wakeword-files/raw/refs/heads/main/mute_switch_on.wav
      - id: mute_switch_off_sound
        file: https://github.com/WarLion/wakeword-files/raw/refs/heads/main/mute_switch_off.wav     
      - id: timer_finished_wave_file
        file: https://github.com/WarLion/wakeword-files/raw/refs/heads/main/timer_finished.wav
      - id: boot
        file: https://github.com/WarLion/wakeword-files/raw/refs/heads/main/wake_word_triggered.wav

voice_assistant:
  id: va
  microphone: mic
  media_player: media_playerid
  use_wake_word: true
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 5.0

  on_timer_finished:
    - switch.turn_on: timer_ringing  
    - wait_until:
        - switch.is_off: timer_ringing
    - voice_assistant.start_continuous:

  on_wake_word_detected:
    - light.turn_on:
        id: status_led
        brightness: 100%
        red: 0%
        green: 50%
        blue: 90%

  on_listening:
    - light.turn_on:
        id: status_led
        effect: "Scan"
        brightness: 95%
        red: 2%
        green: 13%
        blue: 100%     
 
  on_stt_end:
    - light.turn_on:
        id: status_led
        effect: "Slow Pulse"
        brightness: 95%
        red: 10%
        green: 80%
        blue: 10%

  on_error:
    - light.turn_on:
        id: status_led
        red: 100%
        green: 0%
        blue: 0%
        effect: "Fast Pulse"

  on_tts_start:
    - light.turn_on:
        id: status_led
        effect: "Scan"

  on_end:
    - if:
        condition:
          - switch.is_on: mute_va
        then:
          - light.turn_on:
              id: status_led
              effect: "Slow Pulse"
              brightness: 95%
              red: 80%
              green: 80%
              blue: 10%
        else:
          - if:
              condition: 
                - switch.is_on: timer_ringing
              then:
                - light.turn_on:
                    id: status_led
                    red: 100%
                    green: 0%
                    blue: 0%
                    effect: "Timer Alert"  
                    brightness: 100%
              else:
                - light.turn_off: status_led


switch:
  - platform: template
    name: "Mute"
    id: mute_va
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - voice_assistant.stop:
      - script.execute:
          id: play_sound
          priority: false
          sound_file: !lambda return id(mute_switch_on_sound);   
    turn_off_action:
      - script.execute:
          id: play_sound
          priority: false
          sound_file: !lambda return id(mute_switch_off_sound);   
      - delay: 1s
      - media_player.stop
      - light.turn_off: status_led
      - delay: 30ms
      - voice_assistant.start_continuous:

  - platform: template
    id: timer_ringing
    name: "Timer"
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_off:
      - light.turn_off:
          id: status_led    
      # Turn off the repeat mode and disable the pause between playlist items
      - lambda: |-
              id(media_playerid)
                ->make_call()
                .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_REPEAT_OFF)
                .set_announcement(true)
                .perform();
              id(media_playerid)->set_playlist_delay_ms(speaker::AudioPipelineType::ANNOUNCEMENT, 0);
      # Stop playing the alarm
      - media_player.stop:
          announcement: true
    on_turn_on:
      - voice_assistant.stop:
      - wait_until:
          not:
            microphone.is_capturing: 
      - lambda: |-
            id(media_playerid)
              ->make_call()
              .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_REPEAT_ONE)
              .set_announcement(true)
              .perform();
            id(media_playerid)->set_playlist_delay_ms(speaker::AudioPipelineType::ANNOUNCEMENT, 1000);
      - media_player.speaker.play_on_device_media_file:
          media_file: timer_finished_wave_file
          announcement: true    
      - delay: 15min
      - switch.turn_off: timer_ringing
   


light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: "Status LED"
    chipset: WS2812
    pin: ${ledpin}
    num_leds: ${numleds}
    rgb_order: GRB
    restore_mode: ALWAYS_OFF      
    effects:
        - pulse:
            name: "Slow Pulse"
            transition_length: 250ms
            update_interval: 250ms
            min_brightness: 50%
            max_brightness: 100%
        - pulse:
            name: "Fast Pulse"
            transition_length: 100ms
            update_interval: 100ms
            min_brightness: 50%
            max_brightness: 100%
        - addressable_scan:
            name: "Scan"
            move_interval: 50ms
            scan_width: 2
        - addressable_lambda:
            name: Volume Level Display
            update_interval: 500ms
            lambda: |-
              float volume = id(media_playerid).volume;
              int num_leds_on = round(volume * 4);
              for (int i = 0; i < it.size(); i++) {
                if (i < num_leds_on) {
                  it[i] = Color(0, 0, 255); // Blue
                } else {
                  it[i] = Color::BLACK;
                }
              }  
        - pulse:  # ❌ This is misaligned. It's outside the 'effects:' block.
            name: "Timer Alert"
            transition_length: 500ms
            update_interval: 500ms
            min_brightness: 50%
            max_brightness: 100%    

binary_sensor:
  - platform: gpio
    pin:
      number: ${vol_up}
      mode: INPUT_PULLUP
      inverted: true
    id: vol_up
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - switch.toggle: mute_va
    - timing:
        - ON for at most 0.5s
        - OFF for at least 0.5s
      then:
      - if:
          condition:
            - switch.is_on: mute_va
          then:
            - switch.turn_off: mute_va
          else:   
            - if:
                condition: 
                  - switch.is_on: timer_ringing
                then:
                  - switch.turn_off: timer_ringing
                else:        
                  - delay: 30ms
                  - media_player.volume_up:
                  - delay: 30ms

  - platform: gpio
    pin:
      number: ${vol_down}
      mode: INPUT_PULLUP
      inverted: true
    id: vol_down
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - switch.toggle: mute_va
    - timing:
        - ON for at most 0.5s
        - OFF for at least 0.5s
      then:
      - if:
          condition:
            - switch.is_on: mute_va
          then:
            - switch.turn_off: mute_va
          else:         
            - if:
                condition: 
                  - switch.is_on: timer_ringing
                then:
                  - switch.turn_off: timer_ringing
                else:        
                  - delay: 30ms
                  - media_player.volume_down:
                  - delay: 30ms


button:
  - platform: restart
    name: "Restart"
    id: but_rest

script:
  - id: play_sound
    parameters:
      priority: bool
      sound_file: "audio::AudioFile*"
    then:
      - lambda: |-
          if (priority) {
            id(media_playerid)
              ->make_call()
              .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_STOP)
              .set_announcement(true)
              .perform();
          }
          if ( (id(media_playerid).state != media_player::MediaPlayerState::MEDIA_PLAYER_STATE_ANNOUNCING ) || priority) {
            id(media_playerid)
              ->play_file(sound_file, true, false);
          }