blueprint:
  name: Movimiento - Luz Automática en Estacionamiento
  description: >
    Enciende una luz cuando se detecta movimiento después del atardecer y la apaga
    10 minutos después de que ya no haya movimiento.
  domain: automation
  input:
    motion_sensor:
      name: Sensor de movimiento
      description: Sensor que detecta movimiento.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Luz a controlar
      description: Luz que se encenderá y apagará.
      selector:
        entity:
          domain: light
    delay_off:
      name: Tiempo de espera para apagar
      description: Tiempo sin movimiento antes de apagar la luz.
      default: "00:10:00"
      selector:
        duration:

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"

condition:
  - condition: sun
    after: sunset
    before: sunrise
  - condition: state
    entity_id: !input light_target
    state: "off"

action:
  - service: light.turn_on
    target:
      entity_id: !input light_target
  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_sensor
        to: "off"
        for: !input delay_off
  - service: light.turn_off
    target:
      entity_id: !input light_target

mode: restart
